### ISSUE TITLE
miui12有自带忽略权限吧？

### ISSUE THREAD

**Issue by aabababb** [ikas-mc/px-app#3]
miui12有自带忽略权限吧？
还需要这个插件么？
而且要先装sui,才能用？

**Comment by ikas-mc** [comment]
@aabababb 没有必要,也不建议用

**Comment by ikas-mc** [comment]
这个插件主要是拦截所有appops的修改,这样实现安卓10之前那种appops控制效果

**Comment by ikas-mc** [comment]
管理app需要root或者sui才行的.
